### ISSUE TITLE
2889 enum bug

### ISSUE THREAD

**Issue by leonardhyu** [xenanetworks/open-automation-test-suites#24]
PFA script file and json file.
```
16:05:09.867 | /home/ravindra/xena_automation_new/pluginlib2889/plugin2889/test_manager.py:30 __aexit__ | invoked <class 'KeyError'> 'FIELD_1E6_BPS' <traceback object at 0x7f392c7514c0>
Exception in callback SuiteExecutor.__on_execution_terminated(<Task finishe...ELD_1E6_BPS')>)
handle: <Handle SuiteExecutor.__on_execution_terminated(<Task finishe...ELD_1E6_BPS')>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ravindra/venv/lib/python3.8/site-packages/xoa_core/core/executors/executor.py", line 52, in __on_execution_terminated
    raise e
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/__init__.py", line 55, in start
    await self.__do_test()
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/__init__.py", line 49, in __do_test
    await test_suit_class(plugin_params, test_suit_config).start()
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/plugin/test_abstract.py", line 86, in start
    await self.do_test_logic()
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/plugin/base_class.py", line 274, in do_test_logic
    await self.run_test(run_props)
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/plugin/test_forward_pressure.py", line 142, in run_test
    await self.resources.set_stream_rate_and_packet_limit(run_props.packet_size, const.DECIMAL_100, self.test_suit_config.duration)
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/resource/manager.py", line 171, in set_stream_rate_and_packet_limit
    await asyncio.gather(*coroutines)
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/resource/_port_stream.py", line 159, in set_rate_and_packet_limit
    await self.set_rate_and_packet_limit_fraction(packet_size, rate_percent, traffic_duration, rate_definition)
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/resource/_port_stream.py", line 118, in set_rate_and_packet_limit_fraction
    port_speed = await self.__resource.get_used_port_speed()
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/resource/test_resource.py", line 112, in get_used_port_speed
    port_cap_rate = self.port_config.port_rate_cap_value * self.port_config.port_rate_cap_unit.to_int
  File "/home/ravindra/xena_automation_new/pluginlib2889/plugin2889/const.py", line 225, in to_int
    return PortRateCapUnitInt[self.name].value
  File "/usr/lib/python3.8/enum.py", line 387, in __getitem__
    return cls._member_map_[name]
KeyError: 'FIELD_1E6_BPS'
```

**Comment by fpfeng** [comment]
fixed in 1.0.2
